#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if ! command -v xcodebuild >/dev/null 2>&1; then
  echo "xcodebuild not found. Install Xcode and try again."
  exit 1
fi

if ! command -v xcrun >/dev/null 2>&1; then
  echo "xcrun not found. Install Xcode Command Line Tools and try again."
  exit 1
fi

# Use the package's implicit scheme (auto-generated by xcodebuild from Package.swift's
# library target). No shared .xcscheme file is required for a SwiftPM package.
SCHEME="KrdpassAuth"

SIMULATOR_ID="$(
  python3 - <<'PY'
import json, subprocess
out = subprocess.check_output(['xcrun', 'simctl', 'list', 'devices', '-j'])
data = json.loads(out)
devices = data.get("devices", {})
booted = []
available = []
for runtime, items in devices.items():
    if "iOS" not in runtime:
        continue
    for d in items:
        if not d.get("isAvailable"):
            continue
        if d.get("state") == "Booted":
            booted.append(d["udid"])
        else:
            available.append(d["udid"])
print((booted[0] if booted else (available[0] if available else "")))
PY
)"

if [[ -z "${SIMULATOR_ID}" ]]; then
  echo "No available iOS Simulator found. Create one in Xcode > Settings > Platforms."
  exit 1
fi

echo "Running tests with scheme: ${SCHEME}"
echo "Using simulator: ${SIMULATOR_ID}"

# Ensure simulator is booted and ready
if ! xcrun simctl list devices | grep -q "${SIMULATOR_ID} (Booted)"; then
  xcrun simctl boot "${SIMULATOR_ID}" >/dev/null 2>&1 || true
fi
xcrun simctl bootstatus "${SIMULATOR_ID}" -b

xcodebuild \
  -scheme "${SCHEME}" \
  -destination "platform=iOS Simulator,id=${SIMULATOR_ID}" \
  test
